version: 2.1
jobs:
  build:
    docker:
      - image: cimg/node:18.20.5
    working_directory: ~/project/client
    steps:
      - checkout
      - run:
          name: List files in root directory
          command: ls -al ~/project
      - run:
          name: List files in client directory
          command: ls -al ~/project/client
      - run:
          name: Show Vite config (if exists)
          command: |
            if [ -f vite.config.js ]; then cat vite.config.js; fi
            if [ -f vite.config.ts ]; then cat vite.config.ts; fi
      - restore_cache:
          keys:
            - npm-cache-{{ checksum "package-lock.json" }}
            - npm-cache-
      - run:
          name: Install dependencies
          command: npm ci
      - save_cache:
          key: npm-cache-{{ checksum "package-lock.json" }}
          paths:
            - ~/.npm
      - run:
          name: Build Vite project
          command: npm run build
      - persist_to_workspace:
          root: dist
          paths:
            - .
      - store_artifacts:
          path: dist
          destination: dist
workflows:
  build_and_store:
    jobs:
      - build