version: 2.1
executors:
  android-executor:
    docker:
      - image: cimg/android:2024.01.1
    working_directory: ~/project
jobs:
  build-apk:
    executor: android-executor
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: ./gradlew dependencies
      - run:
          name: Clear Gradle cache
          command: rm -rf ~/.gradle/caches
      - run:
          name: Disable Gradle Daemon
          command: echo "org.gradle.daemon=false" >> ~/.gradle/gradle.properties
      - run:
          name: Build APK
          command: ./gradlew assembleRelease
      - store_artifacts:
          path: app/build/outputs/apk/release/app-release.apk
          destination: app-release.apk
workflows:
  version: 2
  build:
    jobs:
      - build-apk