version: 2.1
executors:
  node-executor:
    docker:
      - image: cimg/node:18.20.5
    working_directory: ~/project
jobs:
  build:
    executor: node-executor
    steps:
      - checkout
      - restore_cache:
          keys:
            - npm-cache-{{ checksum "package-lock.json" }}
            - npm-cache-
      - run:
          name: Install npm dependencies
          command: npm ci
      - run:
          name: Build server only
          command: esbuild server/index.ts --platform=node --packages=external --bundle --format=esm --outdir=dist
workflows:
  version: 2
  build-only:
    jobs:
      - build