version: 2.1
executors:
  node-executor:
    docker:
      - image: cimg/node:18.20.2
    working_directory: ~/project/react
jobs:
  build-react:
    executor: node-executor
    steps:
      - checkout
      - restore_cache:
          keys:
            - npm-cache-{{ checksum "package-lock.json" }}
            - npm-cache-
      - run:
          name: Install dependencies
          command: npm ci
      - save_cache:
          paths:
            - ~/.npm
          key: npm-cache-{{ checksum "package-lock.json" }}
      - run:
          name: Build React app
          command: npm run build
      - store_artifacts:
          path: build
          destination: react-build
workflows:
  version: 2
  build_and_store:
    jobs:
      - build-react
