version: 2.1
executors:
  flutter-executor:
    docker:
      - image: cirrusci/flutter:latest
    working_directory: ~/project
jobs:
  build-apk:
    executor: flutter-executor
    steps:
      - checkout
      - run:
          name: Install Flutter dependencies
          command: flutter pub get
      - run:
          name: Build APK
          command: flutter build apk --release
      - store_artifacts:
          path: build/app/outputs/flutter-apk/app-release.apk
          destination: app-release.apk
workflows:
  build:
    jobs:
      - build-apk
