version: 2.1
executors:
  node-executor:
    docker:
      - image: cimg/node:18.20.5
    working_directory: ~/project
jobs:
  build-typescript:
    executor: node-executor
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: yarn install --frozen-lockfile
      - run:
          name: Build TypeScript
          command: yarn build
workflows:
  version: 2
  build_and_test:
    jobs:
      - build-typescript
